name: Test

on:
  workflow_call:
    inputs:
      remote_port:
        type: string
        required: true
      dig_type:
        type: string
        required: true
      remote_host:
        type: string
        required: true
      remote_resolve:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      remote_port:
        description: remote_port
        type: string
        required: true
      dig_type:
        description: dig_type
        type: string
        required: true
      remote_host:
        description: remote_host
        type: string
        required: true
      remote_resolve:
        description: remote_resolve
        type: string
        required: true


defaults:
  run:
    shell: bash


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        docker_image: ["debian:bullseye", "debian:bookworm", "ubuntu:24.04", "ubuntu:22.04"]
        PROXY_IP: ["127.0.0.1:59999", "[::1]:59999"]
        REMOTE_DOMAIN: ["icanhazip.com"]
        os: ["ubuntu-latest", "ubuntu-24.04-arm"]
    env:
      NGINX_STREAM_LISTEN_PORT: 19000
      NGINX_HTTP_LISTEN_PORT: 19001
      PROXY_QUERY_COUNT: 30
      PROXY_QUERY_ROUNDWAIT: 1
      PROXY_IP: ${{ matrix.PROXY_IP }}
      REMOTE_DOMAIN: ${{ matrix.REMOTE_DOMAIN }}
      REMOTE_PORT: ${{ inputs.remote_port }}
      DIG_TYPE: ${{ inputs.dig_type }}
      REMOTE_HOST: ${{ inputs.remote_host }}
      REMOTE_RESOLVE: ${{ inputs.remote_resolve }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: read
    timeout-minutes: 10
    container:
      image: ${{ matrix.docker_image }}
    name: "Test in ${{ matrix.docker_image }} on ${{ matrix.os }} (Proxy IP ${{ matrix.PROXY_IP }}) (Remote Domain ${{ matrix.REMOTE_DOMAIN }}) (Remote Port ${{ inputs.remote_port }}) (Dig type ${{ inputs.dig_type }}) (Remote Host ${{ inputs.remote_host }}) (Remote resolve ${{ inputs.remote_resolve }})"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup
        run: |
          apt-get update
          apt-get -y install openssl libssl-dev
          echo "ARTIFACT_NAME_SUFFIX=$(openssl rand -hex 32)-$(date +%s%N)" >> $GITHUB_ENV

      - name: Install packages
        run: |
          apt-get -y update
          apt-get -y install curl wget git ca-certificates tar build-essential libc6 libpcre3-dev openssl libssl-dev zlib1g-dev dnsutils
      
      - name: Compile Nginx (no socks5)
        run: |
          cp auto/configure .
          chmod +x configure
          ./configure
          make
          ./configure --with-stream
          make
          ./configure --with-debug
          make
          ./configure --with-http_ssl_module
          make
          ./configure --with-stream --with-debug
          make
          ./configure --with-debug --with-http_ssl_module
          make
          ./configure --with-stream --with-http_ssl_module
          make
          ./configure --with-stream --with-debug --with-http_ssl_module
          make
      
      - name: Compile Nginx
        run: |
          ./configure --with-socks5 --with-stream --with-debug --with-http_ssl_module
          make
      
      - name: Install goproxy
        if: ${{ runner.arch == 'ARM64' }}
        run: |
          wget --no-verbose -O "proxy.tar.gz" "https://github.com/snail007/goproxy/releases/download/v15.0/proxy-linux-arm64-v8.tar.gz"
          tar -xf proxy.tar.gz
          chmod +x proxy
      
      - name: Install goproxy
        if: ${{ runner.arch == 'X64' }}
        run: |
          wget --no-verbose -O "proxy.tar.gz" "https://github.com/snail007/goproxy/releases/download/v15.0/proxy-linux-amd64.tar.gz"
          tar -xf proxy.tar.gz
          chmod +x proxy

      - name: Setup goproxy
        run: |
          if [[ -z "$REMOTE_HOST" ]]; then
            REMOTE_HOST=$(dig +short $DIG_TYPE $REMOTE_DOMAIN | head -1 | tr -d '\n')
            if [[ "$DIG_TYPE" == "AAAA" ]]; then
              REMOTE_HOST="[$REMOTE_HOST]"
            fi
            echo REMOTE_HOST="$REMOTE_HOST:$REMOTE_PORT" >> $GITHUB_ENV
          else
            echo PROXY_DNS="--dns-address "8.8.8.8:53" --dns-ttl 300" >> $GITHUB_ENV
          fi
      
      - name: Setup hosts
        run: |
          cat << EOF >> /etc/hosts
          127.0.0.1  $REMOTE_DOMAIN
          EOF
          cat /etc/hosts
      
      - name: Setup Nginx
        run: |
          rm -rf logs
          mkdir -p logs
          echo | tee logs/access.log
          echo | tee logs/error.log
          cat << EOF > conf/nginx.conf

          user  root;
          worker_processes  1;
          error_log  logs/error.log  debug;

          events {
              worker_connections  1024;
          }

          http {
              socks5_timeout 3;

              upstream http-test {
                  server $REMOTE_HOST socks5=$PROXY_IP $REMOTE_RESOLVE;
              }

              server {
                  listen  $NGINX_HTTP_LISTEN_PORT;
                  location / {
                      proxy_ssl_server_name    on;
                      proxy_ssl_name           $REMOTE_DOMAIN;
                      proxy_ssl_protocols      TLSv1.2  TLSv1.3;
                      proxy_pass               https://http-test;
                      proxy_http_version       1.1;
                      proxy_set_header         Host  $REMOTE_DOMAIN;
                      proxy_ssl_session_reuse  off;
                  }
              }
          }

          stream {
              socks5_timeout 3;

              upstream stream-test {
                  server $REMOTE_HOST socks5=$PROXY_IP $REMOTE_RESOLVE;
              }

              server {
                  listen $NGINX_STREAM_LISTEN_PORT;
                  proxy_pass stream-test;
              }
          }

          EOF
      
      - name: Run
        run: |
          objs/nginx -V
          objs/nginx -p $(pwd) -t
          objs/nginx -p $(pwd) -g "daemon on;"
          ./proxy --trace socks --always -t tcp -p "$PROXY_IP" $PROXY_DNS --daemon --log proxy.log
          declare -i max_query_count=$PROXY_QUERY_COUNT
          declare -i i_count=0
          while [ $i_count -le $max_query_count ]; do
            i_count+=1
            if cat proxy.log | grep socks > /dev/null; then
              break;
            elif [[ $i_count -eq $max_query_count ]]; then
              echo "QUERY FAILURE."
              exit 1;
            fi
            sleep $PROXY_QUERY_ROUNDWAIT
          done
          touch curl-output.log
      
      - name: Test stream
        run: |
          curl -s --connect-timeout 5 "https://${REMOTE_DOMAIN}:${NGINX_STREAM_LISTEN_PORT}" --header "Host: ${REMOTE_DOMAIN}" 2>&1 >> curl-output.log
          curl -s --connect-timeout 5 "https://${REMOTE_DOMAIN}:${NGINX_STREAM_LISTEN_PORT}" --header "Host: ${REMOTE_DOMAIN}" 2>&1 >> curl-output.log
          curl -s --connect-timeout 5 "https://${REMOTE_DOMAIN}:${NGINX_STREAM_LISTEN_PORT}" --header "Host: ${REMOTE_DOMAIN}" 2>&1 >> curl-output.log
      
      - name: Test HTTP
        run: |
          curl -s --connect-timeout 5 "http://${REMOTE_DOMAIN}:${NGINX_HTTP_LISTEN_PORT}" --header "Host: ${REMOTE_DOMAIN}" 2>&1 >> curl-output.log
          curl -s --connect-timeout 5 "http://${REMOTE_DOMAIN}:${NGINX_HTTP_LISTEN_PORT}" --header "Host: ${REMOTE_DOMAIN}" 2>&1 >> curl-output.log
          curl -s --connect-timeout 5 "http://${REMOTE_DOMAIN}:${NGINX_HTTP_LISTEN_PORT}" --header "Host: ${REMOTE_DOMAIN}" 2>&1 >> curl-output.log
      
      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          path: |
            **/proxy.log
            **/curl-output.log
            logs/*
            conf/nginx.conf
          retention-days: 1
          overwrite: true
          name: Action-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-${{ env.ARTIFACT_NAME_SUFFIX }}
